#!/bin/bash
# author: Kyle Thomas
# USAGE: $blah <word1>[, <word2>,..., <wordN>]
#JOURNAL="./tempJournalTestFile"
JOURNAL="/home/wetlife/journal/contents.tex"
echo "" >> $JOURNAL
echo "\\section*{ `kydate` }" >> $JOURNAL
echo "\\subsection*{ #writtenWithBlahScript }" >> $JOURNAL
echo "${@1}" >> $JOURNAL
