#!/bin/bash
# author: kyle thomas
# Kyle Thomas: "Hashtags is a language!"
# USAGE: $blah <word1>[, <word2>,..., <wordN>]
# EXAMPLE: $blah coolThingToSay 
#JOURNAL="./tempJournalTestFile"
JOURNAL="/home/wetlife/journal/contents.tex"
echo "" >> $JOURNAL
echo "\\section*{ `/usr/local/bin/kydate` }" >> $JOURNAL
echo "\\subsection*{ #writtenWithBlahScript }" >> $JOURNAL
echo "${@:1}" >> $JOURNAL
