#!/bin/bash
if [[ "$#" -eq 1 ]]; then
	xrandr --output VGA-0 --brightness $1 --output HDMI-0 --brightness $1
elif [[ "$#" -eq 2 ]]; then
	xrandr --output VGA-0 --brightness $1 --output HDMI-0 --brightness $2
fi
