#!/bin/bash
# author:kyle thomas
# usage: $journal [topic_name1 topic_name2 ..]
journal="/home/thomasky/journal/contents.tex"
echo "" >> $journal
echo "\\section*{ `/usr/local/bin/kydate` }" >> $journal
echo "\\subsection*{ ${@:1} }" >> $journal
vim $journal
