#!/bin/sh
# USAGE: $ kychangelogger <string1> [... stringN]
# above usage echos strings as separate items to the tail of <pwd>/changelog.md

if [ ! -e ./changelog.md ]
then
  echo "error: ./changelog.md doesn't exist!"
  exit 1
fi

echo -e "-" `date +%C%y.%m.%dat%H:%M` $@ '\n' >> ./changelog.md
