#!/bin/sh
# USAGE: $ kyrenderjournal
# SYNOPSIS: change into journal dir and render journal live w/ latexmk
echo "changing into journal directory"
cd /home/$USER/journal
echo "compile, view, and hot-reload on change"
latexmk -pvc -pdf journal.tex
